# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(694, 844)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(694, 844))
        mainWindow.setMaximumSize(QtCore.QSize(694, 844))
        self.layoutWidget = QtGui.QWidget(mainWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 651, 791))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit_db = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_db.setObjectName(_fromUtf8("lineEdit_db"))
        self.horizontalLayout.addWidget(self.lineEdit_db)
        self.addFolder_db = QtGui.QPushButton(self.layoutWidget)
        self.addFolder_db.setObjectName(_fromUtf8("addFolder_db"))
        self.horizontalLayout.addWidget(self.addFolder_db)
        self.addFiles_db = QtGui.QPushButton(self.layoutWidget)
        self.addFiles_db.setObjectName(_fromUtf8("addFiles_db"))
        self.horizontalLayout.addWidget(self.addFiles_db)
        self.build_db = QtGui.QPushButton(self.layoutWidget)
        self.build_db.setObjectName(_fromUtf8("build_db"))
        self.horizontalLayout.addWidget(self.build_db)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit_imgserach = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_imgserach.setObjectName(_fromUtf8("lineEdit_imgserach"))
        self.horizontalLayout_2.addWidget(self.lineEdit_imgserach)
        self.selectFlie_imgsearch = QtGui.QPushButton(self.layoutWidget)
        self.selectFlie_imgsearch.setObjectName(_fromUtf8("selectFlie_imgsearch"))
        self.horizontalLayout_2.addWidget(self.selectFlie_imgsearch)
        self.imgsearch = QtGui.QPushButton(self.layoutWidget)
        self.imgsearch.setObjectName(_fromUtf8("imgsearch"))
        self.horizontalLayout_2.addWidget(self.imgsearch)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEdit_semsearch = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_semsearch.setObjectName(_fromUtf8("lineEdit_semsearch"))
        self.horizontalLayout_3.addWidget(self.lineEdit_semsearch)
        self.semsearch = QtGui.QPushButton(self.layoutWidget)
        self.semsearch.setObjectName(_fromUtf8("semsearch"))
        self.horizontalLayout_3.addWidget(self.semsearch)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.inqeury_num = QtGui.QLineEdit(self.layoutWidget)
        self.inqeury_num.setObjectName(_fromUtf8("inqeury_num"))
        self.horizontalLayout_4.addWidget(self.inqeury_num)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.neuralStyle = QtGui.QPushButton(self.layoutWidget)
        self.neuralStyle.setObjectName(_fromUtf8("neuralStyle"))
        self.verticalLayout.addWidget(self.neuralStyle)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.lineEdit_path = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_path.setObjectName(_fromUtf8("lineEdit_path"))
        self.horizontalLayout_7.addWidget(self.lineEdit_path)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.caption = QtGui.QLineEdit(self.layoutWidget)
        self.caption.setObjectName(_fromUtf8("caption"))
        self.horizontalLayout_5.addWidget(self.caption)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.graphicsView = QtGui.QGraphicsView(self.layoutWidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.Previous = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Previous.sizePolicy().hasHeightForWidth())
        self.Previous.setSizePolicy(sizePolicy)
        self.Previous.setObjectName(_fromUtf8("Previous"))
        self.horizontalLayout_6.addWidget(self.Previous)
        self.Next = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Next.sizePolicy().hasHeightForWidth())
        self.Next.setSizePolicy(sizePolicy)
        self.Next.setObjectName(_fromUtf8("Next"))
        self.horizontalLayout_6.addWidget(self.Next)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Notung", None))
        self.addFolder_db.setText(_translate("mainWindow", "Add Folder", None))
        self.addFiles_db.setText(_translate("mainWindow", "Add Files", None))
        self.build_db.setText(_translate("mainWindow", "Build Database", None))
        self.selectFlie_imgsearch.setText(_translate("mainWindow", "Select FIle", None))
        self.imgsearch.setText(_translate("mainWindow", "image similarity search", None))
        self.semsearch.setText(_translate("mainWindow", "semantic siimlarity search", None))
        self.lineEdit.setText(_translate("mainWindow", "inquery number", None))
        self.neuralStyle.setText(_translate("mainWindow", "Neural Style", None))
        self.lineEdit_3.setText(_translate("mainWindow", "path", None))
        self.lineEdit_2.setText(_translate("mainWindow", "caption", None))
        self.Previous.setText(_translate("mainWindow", "Previous", None))
        self.Next.setText(_translate("mainWindow", "Next", None))

