# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'style_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_styleWindow(object):
    def setupUi(self, styleWindow):
        styleWindow.setObjectName(_fromUtf8("styleWindow"))
        styleWindow.resize(670, 753)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(styleWindow.sizePolicy().hasHeightForWidth())
        styleWindow.setSizePolicy(sizePolicy)
        styleWindow.setMinimumSize(QtCore.QSize(670, 753))
        styleWindow.setMaximumSize(QtCore.QSize(670, 753))
        styleWindow.setModal(False)
        self.layoutWidget = QtGui.QWidget(styleWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 631, 711))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.stylePath = QtGui.QLineEdit(self.layoutWidget)
        self.stylePath.setObjectName(_fromUtf8("stylePath"))
        self.horizontalLayout_13.addWidget(self.stylePath)
        self.selectStyle = QtGui.QPushButton(self.layoutWidget)
        self.selectStyle.setObjectName(_fromUtf8("selectStyle"))
        self.horizontalLayout_13.addWidget(self.selectStyle)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.filePath = QtGui.QLineEdit(self.layoutWidget)
        self.filePath.setObjectName(_fromUtf8("filePath"))
        self.horizontalLayout.addWidget(self.filePath)
        self.selectFIle = QtGui.QPushButton(self.layoutWidget)
        self.selectFIle.setObjectName(_fromUtf8("selectFIle"))
        self.horizontalLayout.addWidget(self.selectFIle)
        self.start = QtGui.QPushButton(self.layoutWidget)
        self.start.setObjectName(_fromUtf8("start"))
        self.horizontalLayout.addWidget(self.start)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.slow = QtGui.QRadioButton(self.layoutWidget)
        self.slow.setChecked(True)
        self.slow.setObjectName(_fromUtf8("slow"))
        self.horizontalLayout_2.addWidget(self.slow)
        self.method = QtGui.QComboBox(self.layoutWidget)
        self.method.setObjectName(_fromUtf8("method"))
        self.method.addItem(_fromUtf8(""))
        self.method.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.method)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.fast = QtGui.QRadioButton(self.layoutWidget)
        self.fast.setChecked(False)
        self.fast.setObjectName(_fromUtf8("fast"))
        self.horizontalLayout_3.addWidget(self.fast)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.learningRate = QtGui.QLineEdit(self.layoutWidget)
        self.learningRate.setObjectName(_fromUtf8("learningRate"))
        self.horizontalLayout_4.addWidget(self.learningRate)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.imgWidth = QtGui.QLineEdit(self.layoutWidget)
        self.imgWidth.setObjectName(_fromUtf8("imgWidth"))
        self.horizontalLayout_6.addWidget(self.imgWidth)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.imgHeight = QtGui.QLineEdit(self.layoutWidget)
        self.imgHeight.setObjectName(_fromUtf8("imgHeight"))
        self.horizontalLayout_7.addWidget(self.imgHeight)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_8.addWidget(self.lineEdit_4)
        self.maxSteps = QtGui.QLineEdit(self.layoutWidget)
        self.maxSteps.setObjectName(_fromUtf8("maxSteps"))
        self.horizontalLayout_8.addWidget(self.maxSteps)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_9.addWidget(self.lineEdit_5)
        self.contentWeight = QtGui.QLineEdit(self.layoutWidget)
        self.contentWeight.setObjectName(_fromUtf8("contentWeight"))
        self.horizontalLayout_9.addWidget(self.contentWeight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_10.addWidget(self.lineEdit_6)
        self.styleWeight = QtGui.QLineEdit(self.layoutWidget)
        self.styleWeight.setObjectName(_fromUtf8("styleWeight"))
        self.horizontalLayout_10.addWidget(self.styleWeight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_11.addWidget(self.lineEdit_7)
        self.tvWeight = QtGui.QLineEdit(self.layoutWidget)
        self.tvWeight.setObjectName(_fromUtf8("tvWeight"))
        self.horizontalLayout_11.addWidget(self.tvWeight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.graphicsView = QtGui.QGraphicsView(self.layoutWidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_3.addWidget(self.graphicsView)

        self.retranslateUi(styleWindow)
        QtCore.QMetaObject.connectSlotsByName(styleWindow)

    def retranslateUi(self, styleWindow):
        styleWindow.setWindowTitle(_translate("styleWindow", "Dialog", None))
        self.selectStyle.setText(_translate("styleWindow", "Select Sytle", None))
        self.selectFIle.setText(_translate("styleWindow", "Select File", None))
        self.start.setText(_translate("styleWindow", "Start", None))
        self.slow.setText(_translate("styleWindow", "Slow", None))
        self.method.setItemText(0, _translate("styleWindow", "L-BFGS", None))
        self.method.setItemText(1, _translate("styleWindow", "SGD", None))
        self.fast.setText(_translate("styleWindow", "Fast", None))
        self.lineEdit.setText(_translate("styleWindow", "Learning Rate", None))
        self.lineEdit_2.setText(_translate("styleWindow", "Image Width", None))
        self.lineEdit_3.setText(_translate("styleWindow", "Image Height", None))
        self.lineEdit_4.setText(_translate("styleWindow", "Max Steps", None))
        self.lineEdit_5.setText(_translate("styleWindow", "Content Weight", None))
        self.lineEdit_6.setText(_translate("styleWindow", "Style Weight", None))
        self.lineEdit_7.setText(_translate("styleWindow", "TV Weight", None))

